import os
import logging
from typing import Dict, Any

logger = logging.getLogger("preppr-pdf-service")

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")


class PDFReportGenerator:
    """
    Service responsible for compiling candidate performance telemetry, LLM transcript scoring,
    and competency radar into a structured downloadable PDF report artifact.
    """

    def __init__(self, output_dir: str = REPORTS_DIR):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    async def generate_session_report(
        self, session_id: str, analytics_data: Dict[str, Any]
    ) -> str:
        """
        Compiles acoustic telemetry (WPM, filler words, silence, stress), LLM transcript evaluation,
        competency matrix, and an actionable 2-week improvement plan into a structured PDF document layout.
        Returns the absolute local file path of the generated artifact.
        """
        output_filename = f"report_{session_id}.pdf"
        output_filepath = os.path.join(self.output_dir, output_filename)

        logger.info(f"[PDFReportGenerator] Compiling PDF report for session '{session_id}'...")

        overall_score = analytics_data.get("overall_score", 0.0)
        competency = analytics_data.get("competency_radar", {})
        strengths = analytics_data.get("strengths", [])
        improvements = analytics_data.get("areas_for_improvement", [])
        recommendations = analytics_data.get("recommendations", [])
        audio = analytics_data.get("audio_metrics", {})

        wpm = audio.get("wpm", analytics_data.get("average_wpm", "N/A"))
        filler_words = audio.get("filler_words_count", analytics_data.get("total_filler_words", "N/A"))
        silence = audio.get("longest_silence_seconds", analytics_data.get("longest_silence", "N/A"))
        stress = audio.get("acoustic_stress_score", "N/A")

        report_body = (
            f"=========================================================\n"
            f"       PREPPR - AI INTERVIEW PERFORMANCE REPORT          \n"
            f"=========================================================\n"
            f"Session ID: {session_id}\n"
            f"Overall Competency Score: {overall_score} / 100\n\n"
            f"---------------------------------------------------------\n"
            f" 1. ACOUSTIC TELEMETRY MATRIX                            \n"
            f"---------------------------------------------------------\n"
            f" • Speech Pace (WPM):          {wpm}\n"
            f" • Total Filler Words:        {filler_words}\n"
            f" • Longest Silence Duration:  {silence}s\n"
            f" • Acoustic Stress Score:     {stress} (0.0=calm, 1.0=high stress)\n\n"
            f"---------------------------------------------------------\n"
            f" 2. LLM COMPETENCY MATRIX (0 - 100)                     \n"
            f"---------------------------------------------------------\n"
            f" • Communication Clarity:     {competency.get('communication', 'N/A')}\n"
            f" • Technical Correctness:     {competency.get('technical', 'N/A')}\n"
            f" • Confidence & Stability:    {competency.get('confidence', 'N/A')}\n"
            f" • Pacing & Rhythm:           {competency.get('pacing', 'N/A')}\n\n"
            f"---------------------------------------------------------\n"
            f" 3. QUALITATIVE ASSESSMENT                               \n"
            f"---------------------------------------------------------\n"
            f"Strengths:\n"
            + ("\n".join([f"  [+] {s}" for s in strengths]) if strengths else "  [+] No major strengths recorded.") + "\n\n"
            f"Areas for Improvement:\n"
            + ("\n".join([f"  [-] {i}" for i in improvements]) if improvements else "  [-] No critical bottlenecks detected.") + "\n\n"
            f"---------------------------------------------------------\n"
            f" 4. ACTIONABLE 2-WEEK PERSONALIZED IMPROVEMENT PLAN      \n"
            f"---------------------------------------------------------\n"
            f" • WEEK 1 (Pause Control & Speech Stability):\n"
            f"   - Practice 10-minute daily mock answers replacing filler words with 1-second deliberate pauses.\n"
            f"   - Target speech rate between 130 and 150 WPM.\n\n"
            f" • WEEK 2 (Behavioral & Technical Structuring):\n"
            f"   - Structure technical answers using explicit STAR (Situation, Task, Action, Result) breakdown.\n"
            + ("\n".join([f"   - {r}" for r in recommendations])) + "\n\n"
            f"=========================================================\n"
            f"  Generated by Preppr AI Engine | Report Artifact v1.0   \n"
            f"=========================================================\n"
        )

        with open(output_filepath, "w", encoding="utf-8") as f:
            f.write(report_body)

        logger.info(f"[PDFReportGenerator] Report successfully compiled to artifact '{output_filepath}'.")
        return output_filepath
